/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTeamMember: typeof import('./src/components/TeamManagement/addTeamMember.vue')['default']
    BindPhoneModal: typeof import('./src/components/BindPhoneModal.vue')['default']
    ContactModal: typeof import('./src/components/ContactModal.vue')['default']
    CreationTypeSelectModal: typeof import('./src/components/CreationTypeSelectModal.vue')['default']
    CreativeDescription: typeof import('./src/components/CreativeDescription.vue')['default']
    CtaSection: typeof import('./src/components/CtaSection.vue')['default']
    DesignFeatureModal: typeof import('./src/components/DesignFeatureModal.vue')['default']
    DesignMatrixSection: typeof import('./src/sections/home/DesignMatrixSection.vue')['default']
    EditMemberDialog: typeof import('./src/components/TeamManagement/EditMemberDialog.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    FabricSection: typeof import('./src/sections/home/FabricSection.vue')['default']
    FeatureCard: typeof import('./src/sections/home/FeatureCard.vue')['default']
    FeaturesSection: typeof import('./src/sections/home/FeaturesSection.vue')['default']
    FeedbackModal: typeof import('./src/components/FeedbackModal.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GallerySection: typeof import('./src/sections/home/GallerySection.vue')['default']
    GradientProgress: typeof import('./src/components/GradientProgress.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeroSection: typeof import('./src/sections/home/HeroSection.vue')['default']
    HistoryCreativeModal: typeof import('./src/components/HistoryCreativeModal.vue')['default']
    ImageItem: typeof import('./src/components/ImageItem.vue')['default']
    ImageParamPopup: typeof import('./src/components/ImageParamPopup.vue')['default']
    ImagePreviewModal: typeof import('./src/components/ImagePreviewModal.vue')['default']
    ImageUploadArea: typeof import('./src/components/ImageUploadArea.vue')['default']
    InfiniteScrollLoader: typeof import('./src/components/InfiniteScrollLoader.vue')['default']
    InspirationLibrary: typeof import('./src/components/InspirationLibrary.vue')['default']
    InspirationValueModal: typeof import('./src/components/InspirationValueModal.vue')['default']
    InvitationCode: typeof import('./src/components/InvitationCode.vue')['default']
    LazyImage: typeof import('./src/components/LazyImage.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    MainImageDisplay: typeof import('./src/components/MainImageDisplay.vue')['default']
    MediaPlayer: typeof import('./src/components/MediaPlayer.vue')['default']
    MembershipModal: typeof import('./src/components/MembershipModal.vue')['default']
    ModelSection: typeof import('./src/sections/home/ModelSection.vue')['default']
    OpneTeamMember: typeof import('./src/components/TeamManagement/OpneTeamMember.vue')['default']
    PaymentModal: typeof import('./src/components/PaymentModal.vue')['default']
    PersonalSettingsModal: typeof import('./src/components/PersonalSettingsModal.vue')['default']
    ProductTutorialModal: typeof import('./src/components/ProductTutorialModal.vue')['default']
    ResetPassword: typeof import('./src/components/ResetPassword.vue')['default']
    ResetPasswordModal: typeof import('./src/components/TeamManagement/ResetPasswordModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollText: typeof import('./src/components/ScrollText.vue')['default']
    StatsSection: typeof import('./src/sections/home/StatsSection.vue')['default']
    SubscriptionManageModal: typeof import('./src/components/SubscriptionManageModal.vue')['default']
    ThumbnailGallery: typeof import('./src/components/ThumbnailGallery.vue')['default']
    TransformRow: typeof import('./src/sections/home/TransformRow.vue')['default']
    UserLogin: typeof import('./src/components/UserLogin.vue')['default']
    VideoOptionsSection: typeof import('./src/components/VideoOptionsSection.vue')['default']
    WatermarkDisclaimerModal: typeof import('./src/components/WatermarkDisclaimerModal.vue')['default']
    WriteOffModal: typeof import('./src/components/WriteOffModal.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
