/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    D: typeof import('./src/components/d.vue')['default']
    DesignMatrixSection: typeof import('./src/sections/home/DesignMatrixSection.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FabricSection: typeof import('./src/sections/home/FabricSection.vue')['default']
    FeatureCard: typeof import('./src/sections/home/FeatureCard.vue')['default']
    FeaturesSection: typeof import('./src/sections/home/FeaturesSection.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GallerySection: typeof import('./src/sections/home/GallerySection.vue')['default']
    GradientProgress: typeof import('./src/components/GradientProgress.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeroSection: typeof import('./src/sections/home/HeroSection.vue')['default']
    ImageParamPopup: typeof import('./src/components/ImageParamPopup.vue')['default']
    ImageUploadArea: typeof import('./src/components/ImageUploadArea.vue')['default']
    InfiniteScrollLoader: typeof import('./src/components/InfiniteScrollLoader.vue')['default']
    InspirationValueModal: typeof import('./src/components/InspirationValueModal.vue')['default']
    LazyImage: typeof import('./src/components/LazyImage.vue')['default']
    LoginUser: typeof import('./src/components/LoginUser.vue')['default']
    MainImageDisplay: typeof import('./src/components/MainImageDisplay.vue')['default']
    MediaPlayer: typeof import('./src/components/MediaPlayer.vue')['default']
    MembershipModal: typeof import('./src/components/MembershipModal.vue')['default']
    ModelSection: typeof import('./src/sections/home/ModelSection.vue')['default']
    ParameterSelectModal: typeof import('./src/components/ParameterSelectModal.vue')['default']
    PaymentModal: typeof import('./src/components/PaymentModal.vue')['default']
    PersonalSettingsModal: typeof import('./src/components/PersonalSettingsModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsSection: typeof import('./src/sections/home/StatsSection.vue')['default']
    SubscriptionManageModal: typeof import('./src/components/SubscriptionManageModal.vue')['default']
    ThumbnailGallery: typeof import('./src/components/ThumbnailGallery.vue')['default']
    TransformRow: typeof import('./src/sections/home/TransformRow.vue')['default']
    UserLogin: typeof import('./src/components/UserLogin.vue')['default']
    WriteOffModal: typeof import('./src/components/WriteOffModal.vue')['default']
  }
  export interface GlobalDirectives {
    UserLogin: typeof import('./src/components/UserLogin.vue')['default']
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
