/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BindPhoneModal: typeof import('./src/components/BindPhoneModal.vue')['default']
    D: typeof import('./src/components/d.vue')['default']
    DesignMatrixSection: typeof import('./src/sections/home/DesignMatrixSection.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FabricSection: typeof import('./src/sections/home/FabricSection.vue')['default']
    FeatureCard: typeof import('./src/sections/home/FeatureCard.vue')['default']
    FeaturesSection: typeof import('./src/sections/home/FeaturesSection.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GallerySection: typeof import('./src/sections/home/GallerySection.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeroSection: typeof import('./src/sections/home/HeroSection.vue')['default']
    LoginUser: typeof import('./src/components/LoginUser.vue')['default']
    ModelSection: typeof import('./src/sections/home/ModelSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsSection: typeof import('./src/sections/home/StatsSection.vue')['default']
    TransformRow: typeof import('./src/sections/home/TransformRow.vue')['default']
    UserLogin: typeof import('./src/components/UserLogin.vue')['default']
  }
}
